export const mendeleevTable = [
  [
    { title: 'H', name: 'ВОДОРОД', mass: 1.008, number: 1, color: 'pink' },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    { title: 'He', name: 'ГЕЛИЙ', mass: 4.003, number: 2, color: 'pink' },
  ],
  [
    {
      title: 'Li',
      name: 'ЛИТИЙ',
      mass: 6.941,
      number: 3,
      color: 'pink',
    },
    {
      title: 'Be',
      name: 'БЕРИЛЛИЙ',
      mass: 9.0122,
      number: 4,
      color: 'pink',
    },
    {
      title: 'B',
      name: 'Бор',
      mass: 10.811,
      number: 5,
      color: 'yellow',
    },
    {
      title: 'С',
      name: 'УГЛЕРОД',
      mass: 12.011,
      number: 6,
      color: 'yellow',
    },
    {
      title: 'N',
      name: 'АЗОТ',
      mass: 14.007,
      number: 7,
      color: 'yellow',
    },
    {
      title: 'O',
      name: 'Кислород',
      mass: 15.999,
      number: 8,
      color: 'yellow',
    },
    {
      title: 'F',
      name: 'ФТОР',
      mass: 18.998,
      number: 9,
      color: 'yellow',
    },
    {},
    {},
    {},
    {
      title: 'Ne',
      name: 'НЕОН',
      mass: 20.179,
      number: 10,
      color: 'yellow',
    },
  ],
  [
    {
      title: 'NA',
      name: 'НАТРИЙ',
      mass: 22.99,
      number: 11,
      color: 'pink',
    },
    {
      title: 'MG',
      name: 'МАГНИЙ',
      mass: 24.312,
      number: 12,
      color: 'pink',
    },
    {
      title: 'Al',
      name: 'АЛЮМИНИЙ',
      mass: 26.092,
      number: 13,
      color: 'yellow',
    },
    {
      title: 'Si',
      name: 'КРЕМНИЙ',
      mass: 28.086,
      number: 14,
      color: 'yellow',
    },
    {
      title: 'P',
      name: 'ФОСФОР',
      mass: 30.974,
      number: 15,
      color: 'yellow',
    },
    {
      title: 'S',
      name: 'СЕРА',
      mass: 32.064,
      number: 16,
      color: 'yellow',
    },
    {
      title: 'Cl',
      name: 'ХЛОР',
      mass: 35.453,
      number: 17,
      color: 'yellow',
    },
    {},
    {},
    {},
    {
      title: 'Ar',
      name: 'Аргон',
      mass: 39.948,
      number: 18,
      color: 'yellow',
    },
  ],
  [
    {
      title: 'K',
      name: 'КАЛИЙ',
      mass: 39.102,
      number: 19,
      color: 'pink',
    },
    {
      title: 'Сa',
      name: 'Кальций',
      mass: 40.08,
      number: 20,
      color: 'pink',
    },
    {
      title: 'Sc',
      name: 'СКАНДИЙ',
      mass: 44.957,
      number: 21,
      color: 'blue',
    },
    {
      title: 'Ti',
      name: 'Титан',
      mass: 47.956,
      number: 22,
      color: 'blue',
    },
    {
      title: 'V',
      name: 'ВАНАДИЙ',
      mass: 50.941,
      number: 23,
      color: 'blue',
    },
    {
      title: 'Cr',
      name: 'Хром',
      mass: 51.996,
      number: 24,
      color: 'blue',
    },
    {
      title: 'Mn',
      name: 'МАРГАНЕЦ',
      mass: 54.938,
      number: 25,
      color: 'blue',
    },
    {
      title: 'Fe',
      name: 'Железа',
      mass: 55.849,
      number: 26,
      color: 'blue',
    },
    {
      title: 'Co',
      name: 'Кобальт',
      mass: 58.933,
      number: 27,
      color: 'blue',
    },
    {
      title: 'Ni',
      name: 'НИКЕЛЬ',
      mass: 58.7,
      number: 28,
      color: 'blue',
    },
    {},
  ],
];

export type ITable = typeof mendeleevTable;

export const SET_SELECTED_ELEMENT = 'SET_SELECTED_ELEMENT';
